const String kChat = 'chat';
const String kText = 'text';
const String kUserId = 'userId';
const String kCreatedAt = 'createdAt';
const kUsers = 'users';
const kUsername = 'username';
const kEmail = 'email';
const kImageUrl = 'imageUrl';
const kUserImage = 'userImage';
